### ISSUE TITLE
Add support for Scala 2.13

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/spark-hats#38]
## Background
It has been requested to be able to use the library in a project built for on Scala 2.13

**Comment by Zejnilovic** [comment]
AFAIK [hats ](https://github.com/AbsaOSS/spark-hats)and https://github.com/AbsaOSS/spark-hofs/issues/19 are for Spark 2. 
Spark 2 does not support Scala 2.13.
Does it make sense to update these to use scala 2.13?

**Comment by yruslan** [comment]
Hofs was created to add functionality missing in Spark 2. But Spark 3 has 'transform' etc. So hofs might become obsolete.

But `hats` adds nice interface on the top of standard functions for better array manipulation. And if it can be rewritten to use standard Spark's `transform()`, it makes sense to still have it in Spark 3.

**Comment by Zejnilovic** [comment]
> Hofs was created to add functionality missing in Spark 2. But Spark 3 has 'transform' etc. So hofs might become obsolete.
> 
> But `hats` adds nice interface on the top of standard functions for better array manipulation. And if it can be rewritten to use standard Spark's `transform()`, it makes sense to still have it in Spark 3.

Ideal to be done as part of https://github.com/AbsaOSS/spark-hats/issues/33

**Comment by benedeki** [comment]
It would be cool, but would require the release to be split to version for Spark 2 and another one for Spark 3 (as [spark-commons](https://github.com/AbsaOSS/spark-commons), and [spark-partition-sizing](https://github.com/AbsaOSS/spark-partition-sizing) have it)

**Comment by yruslan** [comment]
I'm going to go for the same implementation for all Scala versions for now. Optimizing hofs away from Scala 2.12 and Scala 2.13 will be another issue and another PR.

I'll try to remove hofs dependency from Scala 2.12 and Scala 2.13 builds.

**Comment by yruslan** [comment]
Fixed in https://github.com/AbsaOSS/spark-hats/pull/43
